return {
 ["Hledat na webu knihovny"] = "Search on the library site"
 ,["Aktuality"] = "News"
 ,[' (<a href="archiv.html">více</a>)'] = ' (<a href="archive-en.html">more</a>)'    
 ,[ "Katalog"]= "Catalog"
 ,[ "https://ckis.cuni.cz/F/"] =  "https://ckis.cuni.cz/F/?CON_LNG=ENG"
 ,["Klíčová slova:"] = "Keywords:"
 ,["Vyhledat v: "] = "Search in: "
 ,[ "Všechna pole"] = "All fields"
 ,["Název"]="Title"
 ,["První slovo z názvu"]="First title word"
 ,["Autor"]="Author"
 ,["Autorský rejstřík"]="Author index"
 ,["Předmět"]="Subject"
 ,["Předmětový rejstřík"]="Subject index"
 -- ,["ISBN/ISSN"]="ISBN/ISSN"
 ,["hledat"]="search"
 ,["Pokud požadovanou publikaci nemáme, můžete nám dát návrh na její <a href='objednavani_liter.htm'>nákup</a>."]="&nbsp;"
 ,["Ukaž (vyhledávání <abbr title='informační zdroje'>IZ</abbr>)"]="Information resouces"
 ,["E-časopisy"]="E-journals"
 ,[ "Plánované uzavření knihovny"]="Closing days"
 ,["Nové knihy"]="New books"
 ,["feed.rss"] = "feed-en.rss"
 ,[ "img/logo.svg"] =  "img/logo-eng.svg"
 ,[ "index-en.html"] =  "index.html"
 ,[ "img/gb.svg"] =  "img/cz.svg"
 ,[ "English version"] = "Česká verze"
 ,[ "Přehled našich časopisů si můžete prohlédnout <a href='periodika.htm'>zde</a>."] = ""
 ,["Studovna"] = "Studyroom"
 ,["Výpůjční protokol"] = "Library"
 ,["Půjčovna"] = "Library"
 ,["Po"] = "Mo"
 ,["Út–Pá"] = "Tue-Fri"
 ,["Po–Čt"] = "Mo-Thu"
 ,["Pá"] = "Fri"
 ,['js/calendar.js'] = 'js/calendar-en.js'
 ,['Zavírací den'] = "Closing day"
 ,['Dnes má knihovna zavřeno: '] = "The library is closed today:"
 ,['Vánoční prázdniny'] = "Christmas"
 ,['Letní prázdniny'] = "Summer holiday"
 ,['Rektorský den'] = "Rector's day"
 ,['Děkanský den'] = "Dean's day"
 ,['Logo knihovny'] = "Library logo"
 ,['cs'] = "en"
 ,["Klíčová slova:"]="Keywords"

 }
