return {
 ["Hledat na webu knihovny"] = "Search on the library site"
 ,["Aktuality"] = "News"
 ,[' (<a href="archiv.html">archiv</a>)'] = ' (<a href="archive-en.html">archive</a>)'    
 ,[ "Katalog"]= "Catalog"
 ,[ "https://ckis.cuni.cz/F/"] =  "https://ckis.cuni.cz/F/?CON_LNG=ENG"
 ,["Klíčová slova:"] = "Keywords:"
 ,["Vyhledat v: "] = "Search in: "
 ,[ "Všechna pole"] = "All fields"
 ,["Název"]="Title"
 ,["První slovo z názvu"]="First title word"
 ,["Autor"]="Author"
 ,["Autorský rejstřík"]="Author index"
 ,["Předmět"]="Subject"
 ,["Předmětový rejstřík"]="Subject index"
 -- ,["ISBN/ISSN"]="ISBN/ISSN"
 ,["hledat"]="search"
 ,["Pokud požadovanou publikaci nemáme, můžete nám dát návrh na její <a href='bjednavani_liter.htm'>nákup</a>."]="&nbsp;"
 ,["Ukaž"]="Ukaž"
 ,["E-časopisy"]="E-journals"
 ,["Někdy máme také zavřeno"]="Closing days"
 ,["Nové knihy"]="New books"
 ,["feed.rss"] = "feed-en.rss"
 }
